version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 cliSocketSays.py -a 192.168.150.136 -p 7458 -t 'test'
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
